package:
  name: catboost
  version: "1.2"

build:
  number: 1
  #  Yandex supplies whl files on PyPI for:
  # - Linux: Python 3.7, 3.8, 3.9, 3.10, 3.11
  # - OS X: Python 3.7, 3.9, 3.10, 3.11
  # - Win-64: Python 3.7, 3.8, 3.9, 3.10, 3.11
  skip: True  # [win32 or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.16.0                        # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - enum34  # [py27]
    - numpy >=1.16.0
    - pandas >=0.24.0
    - scipy
    - six
    - plotly
    - matplotlib-base
    - python-graphviz
    #python-graphviz avoids the pip check error


test:
  imports:
    - catboost
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://catboost.ai
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/catboost/catboost/blob/master/LICENSE
  summary: 'Gradient boosting on decision trees library'

  description: |
    General purpose gradient boosting on decision trees library with categorical features support out of the box.
    It is easy to install, contains fast inference implementation and supports CPU and GPU (even multi-GPU) computation.
  doc_url: https://catboost.ai/docs/concepts/about.html
  dev_url: https://github.com/catboost/catboost

extra:
  recipe-maintainers:
    - sab
    - kizill
    - nikitxskv
    - dbakshee
    - andrey-khropov
