package:
  name: catboost
  version: "0.22"

build:
  number: 0
  #  Yandex supplies whl files on PyPI for:
  # - Linux: Python 2.7, 3.5, 3.6, 3.7, 3.8
  # - OS X: Python 2.7, 3.5, 3.6, 3.7, 3.8
  # - Win-64: Python 2.7, 3.5, 3.6, 3.7, 3.8
  skip: True  # [win32]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - enum34  # [py27]
    - numpy >=1.16.0
    - pandas >=0.24.0
    - scipy
    - six

test:
  imports:
    - catboost

about:
  home: http://catboost.ai
  license: Apache 2.0
  license_family: MIT
  license_file:
  license_url: https://github.com/catboost/catboost/blob/master/LICENSE
  summary: 'Gradient boosting on decision trees library'

  description: |
    General purpose gradient boosting on decision trees library with categorical features support out of the box.
    It is easy to install, contains fast inference implementation and supports CPU and GPU (even multi-GPU) computation.
  doc_url: https://catboost.ai/docs/concepts/about.html
  dev_url: https://github.com/catboost/catboost

extra:
  recipe-maintainers:
    - sab
    - kizill
    - nikitxskv
    - dbakshee
    - andrey-khropov
