{% set name = "catboost" %}
{% set version = "0.23.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/catboost/catboost/archive/v{{ version }}.tar.gz
  sha256: 789eeded452cb79a822d463df50fe8d2a603a6afed668c029510299907b8f4a1

build:
  number: 2
  skip: True  # [win32 or python_impl == 'pypy']

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - six
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=0.24.0
    - scipy
    - six
    - plotly
    - graphviz
    - scipy
    - matplotlib-base

test:
  imports:
    - catboost
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://catboost.ai
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Gradient boosting on decision trees library'

  description: |
    General purpose gradient boosting on decision trees library with categorical features support out of the box.
    It is easy to install, contains fast inference implementation and supports CPU and GPU (even multi-GPU) computation.
  doc_url: https://catboost.ai/docs/concepts/about.html
  dev_url: https://github.com/catboost/catboost

extra:
  recipe-maintainers:
    - sab
    - kizill
    - nikitxskv
    - dbakshee
    - andrey-khropov
