travis:
  secure:
    BINSTAR_TOKEN: qRP5x9g/ghZCbk9m9+vIi8wweVqCXqwmBq++nUIy7L3RXa0dLVGiSULRfswZNqMsPGvnXXJfWeOL8foB5tO3hewMkncSk0LVRLdwWqk1fNmZ9zMvxzwYvHGca404TsBzviyyqsMW4o/KCmYICks+n0iQIDwUJ7uyaAsWGc7sk3TXBdOqyAhOuGMM7Gh0ghGcLces9iCytkPUixphwsT786jqGRJdNnJ2w2zhP+wEHmbX82L+dfjHNdy3J7ugwX1Ap26Ibwi8Fcnqyx4lXGnxaO7H5imlrgowDz/2gb8kLVqQWIxNVEEH0bJ2uVEGkBaky45SPC44EdDic6iOYGK5q8ow9zxMG26Nx2OmghL0QIZMgDbaF5syFMR8rZ9Q61KZh4HAK8/GEzLCj6Vt7U+v8aVSoDFu5wT8Kpnhcd/DfcKE8WcRU1esb/Xj5ZiKYXTsTPJdDyY5ls3gWZp2hD3avHOPxH0oFejan9CiOroUd5WEBfgIyU10F/b4NqWMBTdUT+NQhvUTgjAOS8HZObcDye5778MlYmWuuy1VMjhL7NeAGXoAkVbYFu19z4rmiMUhviwQyVpx54z7CuJMKi7rD9BVJdsWijsNrMg42ni1TL5QTQ5vd9Xxs2LOMMS29mSckbAIHxNNHVO8ryjIsnfqsXGv4+LvpfDQ0QySUn//1vE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
